### ISSUE TITLE
Alot of Log-Entries per second when using Widget

### ISSUE THREAD

**Issue by T-Ahrens** [centreon/centreon-widget-tactical-overview#15]
Hi,
This my first, be gentle.. ;-)

When i use the widget (v. 19.10.0), i get a lot of entrys in /var/log/httpd/ssl_access_log like this:

 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -
 - - [27/Nov/2019:15:11:24 +0100] "GET /centreon/widgets/tactical-overview/index.php HTTP/1.1" 200 -

are 13 entrys per second normal?
Widget is showing services, we have approx. 3500 Services configured.

best Regards, 
Thorsten

**Comment by tanguyvda** [comment]
Hello Thorsten,

good catch you did there. As you noticed, we have an issue and it has an impact on the performances of the server. You'll see the change you have to do by going there : 
https://github.com/centreon/centreon-widget-tactical-overview/pull/17

To explain what's happening, it is that we have a refresh timer that wasn't set. Meaning that this widget was always trying to refresh itself. 

since you're using the 19.10.0 version, you need to open the /usr/share/centreon/www/widget/tactical-overview/configs.xml file and change 

`<version>19.10.0</version>`

 so it becomes this:
` <version>19.10.0</version>`
when done, head over the administration -> extension menu and update your tactical-overview widget. You'll now be able to edit your widget parameters in your custom view menu. There's also a new option displaying your widget refresh interval.

**Comment by T-Ahrens** [comment]
Hi tanguyvda,

thanks for the Fix.
Do i have to restart centreon after the update, because right now, there's no new options or possibilities to edit parameters?

**Comment by tanguyvda** [comment]
Hi,

no you do not have to restart anything. But I wasn't very clear in my previous answer. 

make sure that: 
**/usr/share/centreon/www/widget/tactical-overview/configs.xml** 
_line 7_
change version to go from 19.10.0 to 19.10.1
_line 18_ 
change the type to go from integer to text 

**/usr/share/centreon/www/widget/tactical-overview/index.php**
_lines 67 and 68_
replace `$preferences['refresh_interval']` with `$preferences['autoRefresh']`

**Comment by T-Ahrens** [comment]
Thanks, that did the trick!

Have a nice day!
